name: Documentation

on:
  push:
    branch: main

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          channels: conda-forge
          auto-update-conda: true

      - name: install requirements
        run: >-
          conda install --file requirements-docs.txt

      - name: install the package
        run: python -m pip install . --no-deps

      - name: build documents
        run: make -C docs html

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
